import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Header } from '../components/chef/header.component'
import { Main } from '../components/chef/header.component'
import { Restri } from '../components/chef/header.component'
export default function Home() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Chef DuLar</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="../public/logo.ico" />
        </Head>
        <Header/>
        <Main/>
        <Restri/>
      </div>
    )
  }
  